name: Executar Script Python Diariamente

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Executar script principal
        run: python src/main.py

      - name: Configurar identidade do commit
        run: |
          git config --global user.name "Igão"
          git config --global user.email "igorbarbosalopes@outlook.com"

      - name: Forçar atualização do arquivo
        run: |
          date >> update-log.txt
          git add update-log.txt

      - name: Configurar git para commit
        run: |
          git config user.name "Igor Lopes"
          git config user.email "igorbarbosalopes@outlook.com"

      - name: Commit e push das mudanças
        run: |
          if [ -f data/latest_data.json ]; then
            git add data/latest_data.json
            git diff --quiet && echo "Sem mudanças para commitar." || (git commit -m "Atualiza notícias automaticamente" && git push)
          else
            echo "Arquivo data/latest_data.json não encontrado, nada para commitar."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
